#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("tech.Resource", IsApplication=true)]

namespace tech
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int navigation_drawer_items_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int contactImage = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int logo = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060013
			public const int BtnLogin = 2131099667;
			
			// aapt resource value: 0x7f06000d
			public const int Imglogo = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int InputPassword = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int InputUsername = 2131099663;
			
			// aapt resource value: 0x7f060003
			public const int ToolBar = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int ToolBar2 = 2131099660;
			
			// aapt resource value: 0x7f060010
			public const int TxtPassword = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int TxtUsername = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int available = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int background = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int content_frame = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int employeelist = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int livefeed = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int livefeedmain = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int main = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int name = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int picture = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int space1 = 2131099656;
			
			// aapt resource value: 0x7f060012
			public const int switch1 = 2131099666;
			
			// aapt resource value: 0x7f060009
			public const int textView1 = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int clients = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EmployeeLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Invalid = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int livefeed = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int people = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
