#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("tech.Resource", IsApplication=true)]

namespace tech
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int navigation_drawer_items_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int contactImage = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monoandroidsplash = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070013
			public const int BtnLogin = 2131165203;
			
			// aapt resource value: 0x7f07000d
			public const int Imglogo = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int InputPassword = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int InputUsername = 2131165199;
			
			// aapt resource value: 0x7f070003
			public const int ToolBar = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int ToolBar2 = 2131165196;
			
			// aapt resource value: 0x7f070010
			public const int TxtPassword = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int TxtUsername = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int available = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int background = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int content_frame = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int employeelist = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int livefeed = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int livefeedmain = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int main = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int name = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int picture = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int space1 = 2131165192;
			
			// aapt resource value: 0x7f070012
			public const int switch1 = 2131165202;
			
			// aapt resource value: 0x7f070009
			public const int textView1 = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int clients = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EmployeeLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Invalid = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int livefeed = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int people = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
